service: localstack-env
plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local
    endpointFile: localstack_endpoints.json

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  metric:
    handler: handler.proxy
    events:
    - http:
        path: metric
        method: post
  query:
    handler: handler.query
    events:
    - http:
        path: metric
        method: get
    